const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const slug = require('slugs');

const beerSchema = new mongoose.Schema({
    name: {
        type: String,
        trim: true, //trims uploaded strings before adding to the db
        required: 'Please enter a beer name!' // could also just put true, however it is better to put an error msg like this
    },
    slug: String,
    description: {
        type: String,
        trim: true,
    },
    pH: Number,
    abv: Number,
    ibu_reported: Number,
    ibu_measured: Number,
    final_gravity: Number,
    srm: Number,
    tags: [String],
    created: {
        type: Date,
        default: Date.now,
    },
    photos: [String],
    brewery: String,
    bjcp_style: String,
    attributes: {
        hoppy: Number,
        bitter: Number,
        malty: Number,
        yeast_character: Number,
        acidic: Number,
        effervescence: Number,
        head_retention: Number,
        color: Number,
        clarity: Number,
        body: Number,
        dryness: Number,
        boozy: Number,
        crushability: Number,
    },
    rating: {
        aroma: {
            score: {
                type: Number,
                min: 0,
                max: 12,
            },
            max_score: {
                type: Number,
                default: 12,
            },
            description: {
                type: String,
                trim: true
            },
        },
        appearance: {
            score: {
                type: Number,
                min: 0,
                max: 3,
            },
            max_score: {
                type: Number,
                default: 3,
            },
            description: {
                type: String,
                trim: true
            },
        },
        flavor: {
            score: {
                type: Number,
                min: 0,
                max: 20,
            },
            max_score: {
                type: Number,
                default: 20,
            },
            description: {
                type: String,
                trim: true
            },
        },
        mouthfeel: {
            score: {
                type: Number,
                min: 0,
                max: 5,
            },
            max_score: {
                type: Number,
                default: 5,
            },
            description: {
                type: String,
                trim: true
            },
        },
        overall: {
            score: {
                type: Number,
                min: 0,
                max: 10,
            },
            max_score: {
                type: Number,
                default: 10,
            },
            description: {
                type: String,
                trim: true
            },
        },
    },
    // author: {
    //     type: mongoose.Schema.ObjectId,
    //     ref: 'User',
    //     required: 'You must supply an author'
    // },
},
// add additional option to display virtual fields (like our reviews field) when displaying store data in JSON or as objects.
// without this, virtual fields would still be present, but they wouldn't be displayed when using res.json(), for example. 
{
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
});

// generate a unique slug from the name
async function setSlug(next) {
    if (!this.isModified('slug')) {
        next();  //skip it
        return;
    };

    this.slug = slug(this.name);
    // before we save a new store with this name, check to see if any other stores with that name already exist in database
    // this is important bc the slug is generated by the name, and the slug is used in the URLs for the indivudal store pages.  So, if the
    // name is the same and the slug is the same, then all stores with the same name will point to the same URL.
    // So... find all the stores with the same name and add a number to the end of the slug to make it unique. 
    const slugRegEx = new RegExp(`^(${this.slug})((-[0-9]*$)?)$`, 'i');
    const existingObjsWithSlug = await this.constructor.find({ slug: slugRegEx });
    
    if (existingObjsWithSlug.length) {
        this.slug = `${this.slug}-${existingObjsWithSlug.length + 1}`;
    }

    next();
}

beerSchema.pre('save', setSlug);


module.exports = mongoose.model('Beer', beerSchema);